2023-10-30 13:25:32 [twisted] CRITICAL: Unhandled error in Deferred:
2023-10-30 13:25:32 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "C:\office\ufso\venv\lib\site-packages\twisted\internet\defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "C:\office\ufso\venv\lib\site-packages\scrapy\crawler.py", line 158, in crawl
    self.engine = self._create_engine()
  File "C:\office\ufso\venv\lib\site-packages\scrapy\crawler.py", line 172, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "C:\office\ufso\venv\lib\site-packages\scrapy\core\engine.py", line 99, in __init__
    self.downloader: Downloader = downloader_cls(crawler)
  File "C:\office\ufso\venv\lib\site-packages\scrapy\core\downloader\__init__.py", line 89, in __init__
    self.handlers: DownloadHandlers = DownloadHandlers(crawler)
  File "C:\office\ufso\venv\lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 34, in __init__
    self._load_handler(scheme, skip_lazy=True)
  File "C:\office\ufso\venv\lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 55, in _load_handler
    dhcls = load_object(path)
  File "C:\office\ufso\venv\lib\site-packages\scrapy\utils\misc.py", line 79, in load_object
    mod = import_module(module)
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\office\ufso\venv\lib\site-packages\scrapy\core\downloader\handlers\datauri.py", line 4, in <module>
    from scrapy.responsetypes import responsetypes
  File "C:\office\ufso\venv\lib\site-packages\scrapy\responsetypes.py", line 139, in <module>
    responsetypes = ResponseTypes()
  File "C:\office\ufso\venv\lib\site-packages\scrapy\responsetypes.py", line 35, in __init__
    self.mimetypes: MimeTypes = MimeTypes()
  File "C:\Program Files\Python38\lib\mimetypes.py", line 68, in __init__
    init()
  File "C:\Program Files\Python38\lib\mimetypes.py", line 353, in init
    db.read_windows_registry()
  File "C:\Program Files\Python38\lib\mimetypes.py", line 262, in read_windows_registry
    continue
KeyboardInterrupt
2023-11-01 11:50:53 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://ufsauto.com/make.html?p=16> (failed 3 times): 500 Internal Server Error
2023-11-01 12:08:21 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://ufsauto.com/make.html?p=16> (failed 3 times): 500 Internal Server Error
2023-11-01 12:08:21 [ufs_auto] ERROR: Internal Server Error on page: https://ufsauto.com/make.html?p=16
2023-11-01 12:15:36 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://ufsauto.com/make.html?p=16> (failed 3 times): 500 Internal Server Error
2023-11-06 10:57:03 [scrapy.core.scraper] ERROR: Spider error processing <GET https://ufsauto.com/make.html?p=1> (referer: None)
Traceback (most recent call last):
  File "C:\office\ufso\venv\lib\site-packages\twisted\internet\defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\office\ufso\venv\lib\site-packages\scrapy\spiders\__init__.py", line 79, in _parse
    return self.parse(response, **kwargs)
  File "C:/office/ufso/ufs_auto/ufs_auto/spiders/test_page_link.py", line 33, in parse
    df = pd.DataFrame({"page_links": self.page_links})
NameError: name 'pd' is not defined
2023-11-06 10:57:40 [scrapy.core.scraper] ERROR: Spider error processing <GET https://ufsauto.com/make.html?p=1> (referer: None)
Traceback (most recent call last):
  File "C:\office\ufso\venv\lib\site-packages\twisted\internet\defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\office\ufso\venv\lib\site-packages\scrapy\spiders\__init__.py", line 79, in _parse
    return self.parse(response, **kwargs)
  File "C:/office/ufso/ufs_auto/ufs_auto/spiders/test_page_link.py", line 33, in parse
    df = pd.DataFrame({"page_links": self.page_links})
NameError: name 'pd' is not defined
2023-11-06 10:58:32 [scrapy.core.scraper] ERROR: Spider error processing <GET https://ufsauto.com/make.html?p=1> (referer: None)
Traceback (most recent call last):
  File "C:\office\ufso\venv\lib\site-packages\twisted\internet\defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\office\ufso\venv\lib\site-packages\scrapy\spiders\__init__.py", line 79, in _parse
    return self.parse(response, **kwargs)
  File "C:/office/ufso/ufs_auto/ufs_auto/spiders/test_page_link.py", line 33, in parse
    df = pd.DataFrame({"page_links": page_links})
NameError: name 'pd' is not defined
2023-11-06 11:01:12 [scrapy.core.scraper] ERROR: Spider error processing <GET https://ufsauto.com/make.html?p=1> (referer: None)
Traceback (most recent call last):
  File "C:\office\ufso\venv\lib\site-packages\twisted\internet\defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\office\ufso\venv\lib\site-packages\scrapy\spiders\__init__.py", line 79, in _parse
    return self.parse(response, **kwargs)
  File "C:/office/ufso/ufs_auto/ufs_auto/spiders/test_page_link.py", line 33, in parse
    df = pd.DataFrame({"page_links": page_links})
NameError: name 'pd' is not defined
2023-11-06 11:02:06 [scrapy.core.scraper] ERROR: Spider error processing <GET https://ufsauto.com/make.html?p=1> (referer: None)
Traceback (most recent call last):
  File "C:\office\ufso\venv\lib\site-packages\twisted\internet\defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\office\ufso\venv\lib\site-packages\scrapy\spiders\__init__.py", line 79, in _parse
    return self.parse(response, **kwargs)
  File "C:/office/ufso/ufs_auto/ufs_auto/spiders/test_page_link.py", line 34, in parse
    df = pd.DataFrame({"page_links": page_links})
NameError: name 'pd' is not defined
2023-11-06 11:02:47 [scrapy.core.scraper] ERROR: Spider error processing <GET https://ufsauto.com/make.html?p=1> (referer: None)
Traceback (most recent call last):
  File "C:\office\ufso\venv\lib\site-packages\twisted\internet\defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\office\ufso\venv\lib\site-packages\scrapy\spiders\__init__.py", line 79, in _parse
    return self.parse(response, **kwargs)
  File "C:/office/ufso/ufs_auto/ufs_auto/spiders/test_page_link.py", line 34, in parse
    df = pd.DataFrame({"page_links": page_links})
NameError: name 'pd' is not defined
2023-11-06 11:03:20 [scrapy.core.scraper] ERROR: Spider error processing <GET https://ufsauto.com/make.html?p=1> (referer: None)
Traceback (most recent call last):
  File "C:\office\ufso\venv\lib\site-packages\twisted\internet\defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\office\ufso\venv\lib\site-packages\scrapy\spiders\__init__.py", line 79, in _parse
    return self.parse(response, **kwargs)
  File "C:/office/ufso/ufs_auto/ufs_auto/spiders/test_page_link.py", line 33, in parse
    df = pd.DataFrame({"page_links": page_links})
NameError: name 'pd' is not defined
